custom: null
darpa:
  data_path: ./datasets/darpa
  dataset_type: rosbag
  horizontal_cells: 512
  horizontal_cells_preprocessing: 512
  neighborhood_side_length:
  - 7
  - 11
  pose_data_path: null
  preprocessed_path: ./datasets/darpa/preprocessed/sequences
  testing_identifiers:
  - 0
  topic: /sherman/lidar_points
  training_identifiers:
  - 0
  vertical_cells: 64
  vertical_field_of_view:
  - -22.5
  - 22.5
epsilon_line: 0.01
epsilon_plane: 0.01
epsilon_range: 0.5
horizontal_field_of_view:
- -179.9
- 179.9
kitti:
  data_path: /disk/vanishing_data/ju878/CODA_for_detection_method/sequences
  dataset_type: kitti
  horizontal_cells: 720
  horizontal_cells_preprocessing: 2250
  neighborhood_side_length:
  - 7
  - 11
  pose_data_path: /disk/vanishing_data/ju878/CODA_for_detection_method/poses
  preprocessed_path: /disk/vanishing_data/ju878/CODA_for_detection_method/preprocessed
  rosbag_path: ''
  testing_identifiers:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 1058
  - 1059
  - 1060
  - 1061
  - 1062
  - 1366
  - 1367
  - 1371
  - 1372
  - 1373
  training_identifiers: []
  vertical_cells: 64
  vertical_field_of_view:
  - -24.5
  - 2.0
min_num_points_in_neighborhood_to_determine_point_class: 10
